# Render deployment configuration
services:
  # Backend Flask API
  - type: web
    name: ai-quiz-backend
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    
  # Frontend Static Site
  - type: static
    name: ai-quiz-frontend
    env: static
    region: oregon
    buildCommand: echo "No build needed for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
